% Erzeuge PKM mit EE-FG 3T0R, deren Beinkette aus Varianten besteht

% Moritz Schappler, moritz.schappler@imes.uni-hannover.de, 2020-07
% (C) Institut für Mechatronische Systeme, Leibniz Universität Hannover

clear
addpath(fullfile(fileparts(which('structgeomsynth_path_init.m')),'struktsynth_par'));
settings = struct( ...
  'EE_FG_Nr', 2, ... % 3T0R
  'dryrun', false, ...
  'check_existing', true, ...
  'selectgeneral', false, ... % nur zur Erzeugung ...
  'selectvariants', true, ... % ... des Namens der Optimierung
  'whitelist_SerialKin', {{'S5PRRRR2V1', 'S5PRRRR3V1', 'S5PRRRR4V1', ...
  'S5PRRRR6V1', 'S5PRRRR7V1', 'S5PRRRR8V1', 'S5PRRRR8V2', 'S5PRRRR9V1', ...
  'S5PRRRR10V1'}}, ...
  'ignore_check_leg_dof', true, ... % Funktion zur Schnell-Überprüfung evtl falsch
  'check_resstatus', 0:8, ...
  'comp_cluster', true, ...
  'base_couplings', 4, ... % Debug: nur einzelne Kombinationen
  'plf_couplings', 2, ... % Debug: nur einzelne Kombinationen
  'parcomp_structsynth', 1, ...
  'parcomp_mexcompile', 0, ...
  'max_actuation_idx', 1);
% Zur Auswertung nach Cluster-Berechnung:
% settings.comp_cluster = false;
% settings.offline = true;

parroblib_add_robots_symact